### ISSUE TITLE
update documentation for Debian

### ISSUE THREAD

**Issue by eroux** [ioi/isolate#1]
Debian/stable has `cgroup-tools` supersedding `cgroup-bin` and `cgroup-lite`, this should be reflected in the documentation

**Comment by bblackham** [comment]
Thanks for pointing this out! I just installed a fresh Debian 8.x installation, and it seems that cgroup support is already present through systemd even without cgroup-tools. I've updated the documentation to include instructions for latest Debian stable (some extra kernel command-line arguments are required for full cgroup support).

Please re-open if there's anything else you notice needed for getting isolate running on Debian.
