### ISSUE TITLE
isolate doesn't use passed home dir if ran from su

### ISSUE THREAD

**Issue by shadowninja55** [ioi/isolate#102]
steps:
`su`
`isolate --init`
`isolate --dir=/home/foo/bar --env=HOME=/box --run /bin/ls ~/bar`

result:
`/bin/ls: cannot access '/root/bar': No such file or directory`

it also seems that even if i hardcode in `/box/bar` to the ls part the directory is still not there. so perhaps it's neither mouting nor setting HOME.

**Comment by gollux** [comment]
The `~/bar` is expanded by the shell from which you run `isolate`.

`/box/bar` should not contain the home directory, it should be visiable as `/home/foo/bar` inside the sandbox.

**Comment by shadowninja55** [comment]
ah, that was the issue, thanks a lot!
