### ISSUE TITLE
thread error with nodejs

### ISSUE THREAD

**Issue by firefoxuz** [ioi/isolate#107]
/usr/local/node-14.2.0/bin/node[2]: ../src/node_platform.cc:61:std::unique_ptr node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.\n 1: 0x55732fce64c0 node::Abort() [/usr/local/node-14.2.0/bin/node]\n 2: 0x55732fce6543 [/usr/local/node-14.2.0/bin/node]\n 3: 0x55732fd57c54 [/usr/local/node-14.2.0/bin/node]\n 4: 0x55732fd57d2c node::NodePlatform::NodePlatform(int, v8::TracingController*) [/usr/local/node-14.2.0/bin/node]\n 5: 0x55732fcb47f1 node::InitializeOncePerProcess(int, char**) [/usr/local/node-14.2.0/bin/node]\n 6: 0x55732fcb4c26 node::Start(int, char**) [/usr/local/node-14.2.0/bin/node]\n 7: 0x7ff49649f09b __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]\n 8: 0x55732fc4b74a _start [/usr/local/node-14.2.0/bin/node]

isolate giving above error by running `isolate --run -- /usr/local/node-14.2.0/bin/node script.js`

**Comment by FerasAloudah** [comment]
Hey, @firefoxuz did you manage to fix this? I'm having the same issue and can't seem to find a solution.

**Comment by firefoxuz** [comment]
@FerasAloudah Yeah I found a solution and it worked. But I don't remember the exact solution.
