### ISSUE TITLE
Add git tag for versioned release

### ISSUE THREAD

**Issue by wil93** [ioi/isolate#11]
This is useful for maintaining distribution-specific packages (e.g. it's enough to change v1.1 to v1.2 in the packaging script instead of having to look for the specific commit id)

**Comment by gollux** [comment]
I will do it for the next release.

**Comment by Teyras** [comment]
We (ReCodEx) would appreciate if you tagged the current release too - it's better to say we depend on (and test against) v0.1 than on commit 42deadbeef.
