### ISSUE TITLE
Directory Mount not working ?

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [ioi/isolate#114]
Hi,

I'm completely new to isolate, here is what I ran, and what I got.

#### Command i ran

`isolate --full-env --dir=/tmp --run -- /usr/bin/ls && /usr/bin/python3 main.py`

#### Output

```
dummy_file.txt

OK (0.004 sec real, 0.004 sec wall)
/usr/bin/python3: can't open file 'main.py': [Errno 2] No such file or directory
```

Here what I'm expecting is to run the program which is in `/tmp` directory in my local system, through isolate.

Am I doing anything wrong?

**Comment by gollux** [comment]
You are not telling `isolate` to run it from `/tmp`, but from the current directory.

Besides, mounting a world-writeable directory into the sandbox is not a good idea.
