### ISSUE TITLE
Deployment Using AWS Lambda

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [ioi/isolate#115]
I'm trying to deploy an app with isolate in AWS lambda, and here I'm getting `Must be started as root` error.

AWS Lambda invocations will be done using a non-root user,  even if we build a Docker image with a root user as the default user.

So does anyone know how to overcome this? or any non-Docker solution is also acceptable.

**Comment by gollux** [comment]
I do not know AWS Lambda, but Isolate requires running as real root.
