### ISSUE TITLE
Quotas does not work on BTRFS

### ISSUE THREAD

**Issue by pehrsoderman** [ioi/isolate#12]
If a BTRFS filesystem is mounted, and included in the sandbox using the --dir= command, quotas will fail silently on this filesystem. This allows arbitrary large files to be written to disk. I believe the quotas are still applied to the other filesystems, if any.

The preferable behavior would be that isolate sets up subvolumes and applies quotas on them.

**Comment by gollux** [comment]
Failing silently does not sound good... I checked that isolate checks the return code of the quotactl syscall properly. Could you try to strace it, please?

Generally, I would rather like to avoid lots of code specific to a single filesystem, but if you have an idea for a simple patch, please let us know.

**Comment by gollux** [comment]
As we got no further input on this issue, I am closing it. If anybody is interested in using isolate with btrfs quotas, feel free to reopen.

**Comment by pehrsoderman** [comment]
We stopped using BTRFS for this reason, and worked around it that way. Never got around to doing a systrace. You may want to make a note somewhere in the documentation which filesystems are supported.

**Comment by gollux** [comment]
> You may want to make a note somewhere in the
> documentation which filesystems are supported.

Good idea. I will do that.
