### ISSUE TITLE
Thanks for maintaining and building this isolate environment. my question is, is it necessary to use docker for this isolated environment or can I also go with Linux Ec2 in AWS?

### ISSUE THREAD

**Issue by Rammehar** [ioi/isolate#120]
I have used this isolate in ec2 instance with ubuntu os.  after setting cgroup1 from cgroup2 it works like this as show below image.
<img width="1440" alt="Screenshot 2022-12-23 at 11 06 18 AM" src="https://user-images.githubusercontent.com/8978743/209278980-54deef29-c7e1-418c-a011-d32d15391c43.png">

**Comment by gollux** [comment]
No, it is not necessary to use Docker.

In fact, I advise against running Isolate under Docker. Keep Isolate as close to the kernel as possible to avoid potential interference between Docker's and Isolate's use of control groups.
