### ISSUE TITLE
Running Java and Python programs

### ISSUE THREAD

**Issue by hermanzdosilovic** [ioi/isolate#13]
Hi,

I have a question about using _isolate_. How can I run Java and Python programs with it? I have read all [documentation](http://www.ucw.cz/moe/isolate.1.html) you guys provided, but I really don't understand how can I run Java and Python programs.

Thanks in advance.

Best,
Herman

**Comment by SemaiCZE** [comment]
Hi,

let's start with simple python program:

```{.py}
#!/usr/bin/env python3

print("Hello world!")
```

Now, you initialize isolate with

```{.sh}
$ isolate --cg --init
```

It will print path to working directory of sandbox. Now you copy that python file (assume it's `a.py`) into that path with additinal subdirectory `box`. For example, could be `/var/local/lib/isolate/0/box`. With this done, run that in isolate

```{.sh}
$ isolate --cg --env=HOME=/home/user --run /usr/bin/python3 a.py
```

Python requires passing some enviroment variables. You can tweak that to fit your needs. It should print something like 

```
Hello world!
OK (0.067 sec real, 0.081 sec wall)
```

Don't forget to cleanup the isolate sandbox

```{.sh}
$ isolate --cg --cleanup
```

Please refer to original man page if you want up-to-date documentation, that url you provided may be a bit outdated.

**Comment by hermanzdosilovic** [comment]
Thanks for you quick response. It works as expected. Why does Python require $HOME environment variable?

**Comment by hermanzdosilovic** [comment]
For anybody out there reading this, I have created new issue regarding running Java programs and overhead in it: #14

**Comment by stefano-maggiolo** [comment]
Re python and the requirement of having HOME, we noticed the same in @cms-dev, see [here](https://github.com/cms-dev/cms/blob/0596ab4ba54895ac18f690ef1795dcefd7d05663/cms/grading/Sandbox.py#L479) - I suppose it is used to look for additional packages in ~/.local/lib/python... anyway, as you see in the link, we set it to the sandbox directory.

**Comment by hermanzdosilovic** [comment]
Thanks @stefano-maggiolo

**Comment by andotorg** [comment]
🐂
