### ISSUE TITLE
Running Java progams and Java overhead

### ISSUE THREAD

**Issue by hermanzdosilovic** [ioi/isolate#14]
Hi, I have a question about running Java programs with _isolate_.

I am trying to run a simple Java program, these are steps I made:

1. Init isolate:
    
  ```
  $ isolate --cg --init
  ```
2. Save `Main.class` file to `/var/local/lib/isolate/0/box/` which is compiled version of following program (I compiled it on the same machine, not using isolate):
  
  ```java
  import java.io.BufferedReader;
  import java.io.InputStreamReader;
  import java.io.IOException;

  public class Main {
    public static void main(String[] args) throws IOException {
      BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
      String name = reader.readLine();
      System.out.println("hello, " + name);
    }
  }
  ```
3. Save `input.txt` to `/var/local/lib/isolate/0/box/` with following content:
  
  ```
  world
  ```
4. Run program with isolate:

  ```
  $ isolate -p --cg -i input.txt --run /usr/local/jdk1.8.0_91/bin/java Main
  hello, world
  OK (0.066 sec real, 0.248 sec wall)
  ```

That's fine, but I as soon as I add memory limit, for example `256MB`, I get following error:
```
$ isolate -p -m 256000 --cg -i input.txt --run /usr/local/jdk1.8.0_91/bin/java Main
Error occurred during initialization of VM
Could not reserve enough space for code cache
Exited with error status 1
```

Of course I can add much higher memory limit and everything will work fine:
```
$ isolate -p -m 4096000 --cg -i input.txt --run /usr/local/jdk1.8.0_91/bin/java Main 
hello, world
OK (0.063 sec real, 0.105 sec wall)
```

but how can I then limit my Java code to `256MB`?

So, my question is: How do I need to run Java code using _isolate_ if I want to set some memory limit?

What are the best practices for running Java code with _isolate_?

Thanks in advance,
Herman

**Comment by gollux** [comment]
Basically, the JVM is going to eat lots of memory whatever you do. The size of the VM can be controlled by the -Xmx option of the JVM and the memory limit given to Isolate must be large enough to accomodate this amount of memory and probably a bit more. However, if you restrict VM size too much, the JVM will run its garbage collector frequently, which leads to significant slowdown (sometimes by an order of magnitude).

At the IOI, it ended up with raising all memory limits to a couple of gigabites, so that all reasonable Java programs fit in the memory limit without triggering garbage collection. If anybody has a better idea, please let me know.

**Comment by hermanzdosilovic** [comment]
I am sorry for such a delay about this discussion.

Think I know why there is an error when I try to run it like:
```
$ isolate -p -m 256000 --cg -i input.txt --run /usr/local/jdk1.8.0_91/bin/java Main
```

Option `-m` indicates *per process*, but what if JVM is creating a process that needs more than 256MB. I found that instead of using `-m` and rather `--cg-mem` it works as expected. But now I have another question.

What is the difference between setting the memory limit given to Isolate and setting the JVM memory limit?

```
$ isolate -p --cg-mem 256000 --cg -i input.txt --run /usr/local/jdk1.8.0_91/bin/java Main
$ isolate -p --cg -i input.txt --run -- /usr/lib/jvm/java-8-oracle/bin/java -Xmx256m Main
```


Also, a question. At the IOI, are you raising all memory limits only for Java? If you raise a memory limit only for Java (because of GC) to lets say 4GB, how would you then check if contestant allocated more memory than allowed, let's say 512MB. Am I missing something out here? :smile: Thanks!
