### ISSUE TITLE
Memory corruption bug in cg_init

### ISSUE THREAD

**Issue by andr3eee1** [ioi/isolate#147]
I tried to run isolate on an rpi 4 and a rather strange bug happens, it seems to be a memory corruption bug in cg_init, the file pointer is set with a crazy value.
I attach all the necessary information below
![image](https://github.com/ioi/isolate/assets/81253375/5f48fb84-d248-48e5-931a-c1f91ff796df)
I use cg2 branch and the picture is taken after I manually added debugging symbols in the makefile
The output from `uname -a` is: _Linux raspi 6.5.0-1010-raspi <span>#</span>13-Ubuntu SMP PREEMPT_DYNAMIC Thu Jan 18 09:08:04 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux_

**Comment by gollux** [comment]
Ah, memory allocation in that function was messed up. Could you please check the current master?

**Comment by AlexVasiluta** [comment]
Might this also have been the root cause of #142? 😅
