### ISSUE TITLE
make install exited with error code 1.

### ISSUE THREAD

**Issue by aniketsaurav18** [ioi/isolate#149]
while runnig `make install` the program exited with error code 1.

Below is the output
```
make: pkg-config: No such file or directory
make: pkg-config: No such file or directory
gcc  -o isolate-cg-keeper isolate-cg-keeper.o config.o util.o
/usr/bin/ld: isolate-cg-keeper.o: in function `main':
isolate-cg-keeper.c:(.text+0x660): undefined reference to `sd_notify'
collect2: error: ld returned 1 exit status
make: *** [Makefile:35: isolate-cg-keeper] Error 1
```

**Comment by gollux** [comment]
To quote the README:

> To compile Isolate, you need:
> 
>   - headers for the libcap library (usually available in a libcap-dev package)
> 
>   - headers for the libsystemd library (libsystemd-dev package) for compilation
>     of isolate-cg-keeper
