### ISSUE TITLE
Support for Docker

### ISSUE THREAD

**Issue by raviprakash007** [ioi/isolate#151]
Hi Team,
Is there any plan to support the Docker container? Multiple people are waiting for this feature. Due to absence of the support, we are stuck in implementing an online programming test project (Judge0).

**Comment by ntut-xuan** [comment]
I think it already supported on docker. You need to create a container with privileged.

See: https://github.com/ntut-xuan/NuOJ-Sandbox/blob/main/Dockerfile
See also: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by gollux** [comment]
We do not plan to support running Isolate in containers.

First, we aim for maximum security and the interaction between Docker (or other hypervisor) and any other use of cgroups and namespaces is too complex for us to be confident that it is secure.

Second, Isolate's primary purpose is testing of programs in programming contests. In this setting, precise measurement of run time is crucial and anything else running on the same machine influences run times. Therefore the recommended setup is to use a dedicated machine for testing. This makes any containerization or virtualization pretty much pointless.

Isolate probably runs in containers if they are privileged enough (there are some success reports with privileged Docker), but you are on your own.

**Comment by raviprakash007** [comment]
Perfect, Can isolate Dockerized images run on k8?

**Comment by raviprakash007** [comment]
> I think it already supported on docker. You need to create a container with privileged.
> 
> See: https://github.com/ntut-xuan/NuOJ-Sandbox/blob/main/Dockerfile See also: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

Will the image work on kubernetes?

**Comment by raviprakash007** [comment]
> > > I think it already supported on docker. You need to create a container with privileged.
> > > See: https://github.com/ntut-xuan/NuOJ-Sandbox/blob/main/Dockerfile See also: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
> > 
> > 
> > Will the image work on kubernetes?
> 
> I perviously test it on k8s and it work. But as @gollux said it may not confirm that it's secure to isolate the real environment.

How many languages does it support? Also, Do we need host machine to support CG-v1 or isolate image?

**Comment by ntut-xuan** [comment]
> How many languages does it support? 

I think it doesn't matter about language, if it can install on ubuntu, it should be work.

> Do we need host machine to support CG-v1 or isolate image?

You should make sure the host is supported CGv1.

**Comment by raviprakash007** [comment]
I have kubernetes cluster. How can I make sure that it is having CG-v1 Enabled?

**Comment by ntut-xuan** [comment]
I think that the kubernates CG will depend on your host CG (Since CG is kernel-level architecture), you just need to configure your host to use CG v1.

**Comment by raviprakash007** [comment]
I was trying to run your repo but perhaps, its isolate master branch has moved to support  CG-v2. So compilation is failing

=> ERROR [sandbox 16/20] RUN make install                                                                                                                                                                       0.1s
------                                                                                                                                                                                                                
 > [sandbox 16/20] RUN make install:                                                                                                                                                                                  
0.094 Package libsystemd was not found in the pkg-config search path.                                                                                                                                                 
0.094 Perhaps you should add the directory containing `libsystemd.pc'                                                                                                                                                 
0.094 to the PKG_CONFIG_PATH environment variable                                                                                                                                                                     
0.094 No package 'libsystemd' found
0.095 Package libsystemd was not found in the pkg-config search path.
0.095 Perhaps you should add the directory containing `libsystemd.pc'
0.095 to the PKG_CONFIG_PATH environment variable
0.095 No package 'libsystemd' found
0.095 gcc -std=gnu99 -Wall -Wextra -Wno-parentheses -Wno-unused-result -Wno-missing-field-initializers -Wstrict-prototypes -Wmissing-prototypes -D_GNU_SOURCE  -c -o isolate-cg-keeper.o isolate-cg-keeper.c
0.108 isolate-cg-keeper.c:15:10: fatal error: systemd/sd-daemon.h: No such file or directory
0.108    15 | #include <systemd/sd-daemon.h>
0.108       |          ^~~~~~~~~~~~~~~~~~~~~
0.108 compilation terminated.
0.109 make: *** [Makefile:38: isolate-cg-keeper.o] Error 1
------

**Comment by ntut-xuan** [comment]
ok.

**Comment by raviprakash007** [comment]
Please update the Dockerfile with the following line, (before you clone isolate)

RUN apt install -y libpcap-dev  && apt install   -y libsystemd-dev

**Comment by Amit-K-007** [comment]
> I think it already supported on docker. You need to create a container with privileged.
> 
> See: https://github.com/ntut-xuan/NuOJ-Sandbox/blob/main/Dockerfile
> See also: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

Hi @ntut-xuan , how are you running isolate.service inside the container, as we don't have access to systemctl and systems? Also how are you able to use cgroups for sandboxes?

**Comment by ntut-xuan** [comment]
> > I think it already supported on docker. You need to create a container with privileged.
> > See: https://github.com/ntut-xuan/NuOJ-Sandbox/blob/main/Dockerfile
> > See also: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
> 
> Hi [@ntut-xuan](https://github.com/ntut-xuan) , how are you running isolate.service inside the container, as we don't have access to systemctl and systems? Also how are you able to use cgroups for sandboxes?

Hi, I don't remember that isolate have `isolate.service`, maybe cgroup2 have this feature but in my implementation I just using cgroup1 version. Please remember to enable privilige on docker-compose.

**Comment by RaubCamaioni** [comment]
I run isolate inside of rootless containers with podman.
Mainly for simplified application packaging.
Tested working on latest WSL2 ubuntu (latest WSL2 supports cgroupv2).

You must use the podman containers designed for systemd.
Rootless podman requires proper systemd delegate configuration.

Isolate requires certain permissions inside the rootless podman:
SYS_ADMIN is required PID namespace isolation.
NET_ADMIN is required for network namespace isolation.
SYS_ADMIN is adding many additional capabilities we don't need.
There is probably a way to reduce the permissions of the container even more.

```
# cgroup path: user -> user1000 -> podman -> isolate
/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-932ea2a24e3bc416a4cc59069e808354206f05dd1b2ebd8364de6d01f1be56b8.scope/container/isolate.slice/isolate.service
```

On host delegate config for non-root users:  /etc/systemd/system/user@.service.d/delegate.conf  
```
[Service]
Delegate=cpu cpuset io memory pids
```

Containerfile for building from ubi systemd image.  
```
FROM registry.access.redhat.com/ubi9/ubi-init

RUN dnf update -y && dnf install -y \
  libcap-devel \
  pkg-config \
  systemd-devel \
  git \
  make \
  gcc

RUN cd /tmp && \
  git clone https://github.com/ioi/isolate.git && \
  cd isolate && \
  make isolate && \
  make install

RUN systemctl enable isolate.service
```

Meet isolate-check requirements.  
```
#!/bin/bash

# reduces time complexity, not security relevant
# unable to make work on WSL2
# echo off > /sys/devices/system/cpu/smt/control

echo never > /sys/kernel/mm/transparent_hugepage/enabled
echo never > /sys/kernel/mm/transparent_hugepage/defrag
echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
sysctl -w kernel.randomize_va_space=0
sysctl -w kernel.core_pattern="core"
```

```
$ podman run --cap-add=CAP_SYS_ADMIN --cap-add=CAP_NET_ADMIN -d --name isolate isolate:latest
$ podman exec -it isolate bash
$ isolate --init --cg
/var/local/lib/isolate/0
$ isolate --cg --dir=/bin --run -- /bin/echo "Isolate Rocks!"
Isolate Rocks!
OK (0.003 sec real, 0.024 sec wall)
```
