### ISSUE TITLE
Limitation on number of sandboxes

### ISSUE THREAD

**Issue by raviprakash007** [ioi/isolate#159]
**Sandbox ID out of range (allowed: 0-999)**

We generally can cross the limit of allowed 1000 sandboxes. Cannot we make it depending on the size_t of the system? or a way to restart the couting from 0?

**Comment by gollux** [comment]
The limit on the number of sandboxes is specified in the configuration file, so feel free to change it as you need. However, you also have to assign a range of UIDs with space for all possible sandboxes.
