### ISSUE TITLE
Why aren't permissions restored on `die()`?

### ISSUE THREAD

**Issue by seirl** [ioi/isolate#16]
https://github.com/ioi/isolate/blob/master/isolate.c#L121

This prevents me from doing things in the box if there was some problem in the sandbox, and I have to add checks everytime in my code to see if the permissions are the right ones. What's the rationale?

**Comment by gollux** [comment]
Generally, die() is called when things go seriously wrong and it is hard to tell if their state is safe enough to let a non-root user touch it. However, "isolate --cleanup" should be always able to remove the mess. If it is not in your case, please tell us the circumstances and we will fix it.

**Comment by seirl** [comment]
Okay, I understand the problem better, that makes sense. My issue is that `die()` is called when the binary we try to `execv()` does not exist. Since other errors that would prevent me from touching those files can happen anyway, I'll just add permission checks when retrieving the data. Thanks :)

**Comment by gollux** [comment]
I do not understand why you need to perform any permission checks -- isn't it sufficient to check the exit code of isolate?

**Comment by seirl** [comment]
Not really. I'm using --stdout and --stderr that point to files inside the box and I'd like to get the output even when there's an error.

**Comment by gollux** [comment]
Still, you can distinguish between exit code 1 (failure of the program inside
the box) and 2 (failure of the box itself).

**Comment by seirl** [comment]
Yes, that should work, thanks!
