### ISSUE TITLE
CGoups not found 

### ISSUE THREAD

**Issue by sudo-anony** [ioi/isolate#166]
I am getting this error 
Cannot open /run/isolate/cgroup: No such file or directory

uopn running the following command
isolate --cg -s -b 83 -M /metadata.txt -t 5.0 -x 1.0 -w 10.0 -k 64000 -p60 --cg-timing --cg-mem=128000 -f 1024 -E HOME=/tmp -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -E LANG -E LANGUAGE -E LC_ALL -E JUDGE0_HOMEPAGE -E JUDGE0_SOURCE_CODE -E JUDGE0_MAINTAINER -E JUDGE0_VERSION -d /etc:noexec --run -- /bin/bash $(basename /box/run.sh) < /stdin.txt > /stdout.txt 2> /stderr.txt

**Comment by gollux** [comment]
Is `isolate.service` running?

**Comment by HARIOMARYA** [comment]
I am having the same problem, below is grub file ,and please tell how do i check isolate service is running or not ?
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT="1> -2"
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=10
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash systemd.unified_cgroup_hierarchy=1"

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"

**Comment by gollux** [comment]
`systemctl status isolate.service`

**Comment by sudo-anony** [comment]
@gollux 
When i ran this command `systemctl status isolate.service`
it gives me this message `Unit isolate.service could not be found.`
hence I already installed isolate cause when I hit this isolate --version it gives me a message that I am using version 2.0
`The process isolator 2.0
(c) 2012--2024 Martin Mares and Bernard Blackham
Built on 2024-07-19 from Git commit v2.0-7-g49e0da0
`

**Comment by sudo-anony** [comment]
@gollux 
I have follow this procedure to install isolate
`sudo apt-get update
sudo apt install postgresql postgresql-contrib libpq-dev
sudo apt-get install git build-essential pkg-config libcap-dev libsystemd-dev asciidoc
git clone https://github.com/ioi/isolate.git
cd isolate
make`

**Comment by Naresh-Khatri** [comment]
Im having the same issue. checking status of `isolate.service` gives `Unit isolate.service could not be found.` 

Im using cgroup2 by setting `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1"`

Here's how I have installed isolate on my machine
```
git clone https://github.com/ioi/isolate.git 
cd isolate 
make isolate
make install
```

I have literally wasted over 2 days fixing my sandbox to run properly so any help would be much appreciated! :(

**Comment by gollux** [comment]
As of now, `make install` does not install the systemd service definitions. You need to install `systemd/*` at whatever place your system uses to keep service files.

**Comment by Naresh-Khatri** [comment]
Thank you very much for the reply. Honesty i feel like this library is really cool but in my opinion, all it lacks is a good and thorough installation guide. I followed the man page but couldn't get it to work properly.

**Comment by gollux** [comment]
If your system is Debian-based, you can build Isolate as a Debian package, which then works out of the box. Pre-built packages will be available soon.

**Comment by Naresh-Khatri** [comment]
If you don’t mind, could you provide a brief guide on installing Isolate and getting it working with the --cg flag? I’m not very Linux-savvy and prefer using Docker, so any pointers would be greatly appreciated.

**Comment by Naresh-Khatri** [comment]
I installed Isolate again on a fresh Ubuntu machine using:

```
git clone https://github.com/ioi/isolate.git  
cd isolate  
make  
make install  
```

When I try to initialize a sandbox with isolate --init --cg, I get the following error:
`Cannot open /run/isolate/cgroup: No such file or directory `

Also, `isolate.service` doesn't seem to be present by default, and the manual doesn't mention how to create it. Could you provide guidance on setting up Isolate with the --cg flag?

Thanks for your help!

**Comment by gollux** [comment]
As I already said:

> As of now, `make install` does not install the systemd service definitions. You need to install `systemd/*` at whatever place your system uses to keep service files.

For Ubuntu, it will be `/etc/systemd/system/`. Then run `systemctl daemon-reload` and `systemctl enable --now isolate.service`.
