### ISSUE TITLE
isolate: unrecognized option '--cg-timing'  and annot open /run/isolate/cgroup: No such file or directory

### ISSUE THREAD

**Issue by sudo-anony** [ioi/isolate#167]
I am facing these two error i have create a service for isolate which is working fine it start with no error but I am facing these two issue with this  command I am running
`isolate --cg -s -b 84 -M /metadata.txt -t 5.0 -x 1.0 -w 10.0 -k 64000 -p60 --cg-timing --cg-mem=128000 -f 1024 -E HOME=/tmp -E PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -E LANG -E LANGUAGE -E LC_ALL -E JUDGE0_HOMEPAGE -E JUDGE0_SOURCE_CODE -E JUDGE0_MAINTAINER -E JUDGE0_VERSION -d /etc:noexec --run -- /bin/bash $(basename /box/run.sh) < /stdin.txt > /stdout.txt 2> /stderr.txt`

this is that way I have configure isolate in my ubunut 
`sudo apt-get update
sudo apt install postgresql postgresql-contrib libpq-dev
sudo apt-get install git build-essential pkg-config libcap-dev libsystemd-dev asciidoc
git clone https://github.com/ioi/isolate.git
cd isolate
make

sudo nano /etc/systemd/system/isolatesandbox.service

[Unit]
Description=Isolate Sandbox Service
After=network.target

[Service]
ExecStart=/usr/local/bin/isolate --run -- /bin/bash -c "echo 'Service running'; sleep infinity"
Restart=always
RestartSec=10
Type=simple
User=root
Group=root
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=isolatesandbox

[Install]
WantedBy=multi-user.target

sudo systemctl daemon-reload
sudo systemctl restart isolatesandbox

`

**Comment by gollux** [comment]
Please use the service files from the `systemd` directory in Isolate's repository.

**Comment by gollux** [comment]
You also mentioned `--cg-timing` (BTW it is not a good idea to mix multiple problems in one Github issue). This option no longer exists in Isolate 2.0. The cg-timing mode is now always on.
