### ISSUE TITLE
Cannot create subgroup /sys/fs/cgroup/isolate.slice/isolate.service/daemon: No such file or directory

### ISSUE THREAD

**Issue by sudo-anony** [ioi/isolate#168]
I have created two services one is isolate.service and the other one is slice.service in which I have place the content I am getting from isolate repo. But I am getting this error on start of isolate.service hence isolate.slice is running.

**Comment by gollux** [comment]
What is the output of `systemctl status isolate.service`, `systemctl status isolate.slice`, and `systemd-cgls`?

What distribution of Linux do you use? Does it run on bare metal or in some virtual machine or container?

**Comment by sudo-anony** [comment]
This is the output errrr when i run isolate.service 
`Cannot create subgroup /sys/fs/cgroup/isolate.slice/isolate.service/daemon: No such file or`

and also when I ran service for slice it ran without error with above warning . The error is same for both of these issues,

and I don't know about the `systemd-cgls` I see bunch of issues . I will attach all of these images with them .
![Screenshot from 2024-07-22 14-11-41](https://github.com/user-attachments/assets/e50f75a2-918c-4570-8fa6-aa9e11340225)

**Comment by gollux** [comment]
I would appreciate the rest of `systemd-cgls` output, better as a text file than as a screenshot.

**Comment by sudo-anony** [comment]
[Uploading systemd-cgls.zip…]()

**Comment by gollux** [comment]
I don't know what you did, but I see your comment as a link leading back to this issue's page.

**Comment by sudo-anony** [comment]
[systemd-cgls.TXT](https://github.com/user-attachments/files/16331492/systemd-cgls.TXT)

**Comment by sudo-anony** [comment]
I am not using any container or virtual machine just my local system i am working on .

**Comment by sudo-anony** [comment]
[
![Screenshot from 2024-07-22 18-28-35](https://github.com/user-attachments/assets/c6e89ebc-7a22-4dd1-bdf1-780ed448ecc8)
](url)

**Comment by sudo-anony** [comment]
[
![Screenshot from 2024-07-22 18-28-35](https://github.com/user-attachments/assets/c6e89ebc-7a22-4dd1-bdf1-780ed448ecc8)
](url)

**Comment by gollux** [comment]
Are you sure your system is running with cgroup v2? What is your kernel command line?

**Comment by sudo-anony** [comment]
> Are you sure your system is running with cgroup v2? What is your kernel command line?

![Screenshot from 2024-07-22 18-35-24](https://github.com/user-attachments/assets/a48a5acf-d039-4ae6-84dc-e2b468317a37)

This is what I got in return

**Comment by gollux** [comment]
Ah, you have a setup with combined cgroup v1 and v2. This is currently not supported by Isolate, sorry. Please switch to plain v2.
