### ISSUE TITLE
Memory access violation leads to different outcomes in different envrionments

### ISSUE THREAD

**Issue by ysabih2** [ioi/isolate#169]
We use Isolate to run user-submitted code in a live coding service. We only use `--cg-mem` option to limit memory usage. We've recently noticed that some C/C++ code hangs for a few minutes and the CPU usage 100% unless the containers running the code are stopped. When we run the same code on Docker Desktop, it crashes fast with the error `Caught fatal signal 11`. I've created this issue to make sure that this inconsistency is normal.

Here is a sample C++ code that hangs when executed in a sandbox:
 ```cpp
#include <iostream>
#include <unordered_map>
#include <string>
class Archive
{
    class Record
    {
    public:
        Record(std::string title, std::string content)
        {
            this->title = title;
            this->content = content;
        }
        std::string title;
        std::string content;
    };
public:
    void add(int id, std::string title, std::string content)
    {
        records[id] = new Record(title, content);
    }
    void remove(int id, std::string& title, std::string& content)
    {
        std::unordered_map<int, Record*>::iterator it = records.find(id);
        Record* doc = it->second;
        title = doc->title;
        content = doc->content;
        delete doc;
        records.erase(it);
    }
    void clear()
    {   
        std::unordered_map<int, Record*>::iterator it;
        for (const auto& elem : records) {
            it = records.find(elem.first);
            Record* doc = it->second;
            delete doc;
            records.erase(it);
        }
        records.clear();
    }
private:
    std::unordered_map<int, Record*> records;
};

int main()
{
    Archive archive;
    archive.add(123456, "Title1", "Content1");
    archive.add(123457, "Title2", "Content2");
    std::string title, content;
    archive.remove(123456, title, content);
    std::cout << title << '\n';
    std::cout << content;
    archive.clear();
}
 ```
The code seems to have a memory management issue. The hanging described above only occurs when I compile and run the code in a sandbox on Azure's AKS without the `--mem` option. Adding a limit on address space using `--mem` in addition to `--cg-mem` fixes the issue, but it seems strange that the same code produces different outcomes on environments with the same settings. I ran `isolate-check-environment` on the Docker containers on AKS and Docker Desktop, I had pretty much the same output.
- Docker Desktop:
 ```
Checking for cgroup support for memory ... PASS
Checking for cgroup support for cpuacct ... PASS
Checking for cgroup support for cpuset ... PASS
Checking for swap ... PASS
Checking for CPU frequency scaling ... SKIPPED (not detected)
Checking for Intel frequency boost ... SKIPPED (not detected)
Checking for general frequency boost ... SKIPPED (not detected)
Checking for kernel address space randomisation ... FAIL
WARNING: address space randomisation is enabled.
echo 0 > /proc/sys/kernel/randomize_va_space
Checking for transparent hugepage support ... FAIL
WARNING: transparent hugepages are enabled.
echo never > /sys/kernel/mm/transparent_hugepage/enabled
WARNING: transparent hugepage defrag is enabled.
echo never > /sys/kernel/mm/transparent_hugepage/defrag
WARNING: khugepaged defrag is enabled.
echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag`
 ```
- AKS (Ran the command on a pod):
 ```
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
Checking for cgroup support for memory ... PASS
Checking for cgroup support for cpuacct ... PASS
Checking for cgroup support for cpuset ... PASS
Checking for swap ... PASS
Checking for CPU frequency scaling ... SKIPPED (not detected)  
Checking for Intel frequency boost ... SKIPPED (not detected)  
Checking for general frequency boost ... SKIPPED (not detected)
echo 0 > /proc/sys/kernel/randomize_va_space
Checking for kernel address space randomisation ... FAIL       
WARNING: address space randomisation is enabled.
echo never > /sys/kernel/mm/transparent_hugepage/enabled
Checking for transparent hugepage support ... FAIL
WARNING: transparent hugepages are enabled.
echo never > /sys/kernel/mm/transparent_hugepage/defrag
WARNING: transparent hugepage defrag is enabled.
WARNING: khugepaged defrag is enabled.
echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
command terminated with exit code 1
 ```

My question is the following: Is this difference in outcomes normal when `--mem` option is not used?

**Comment by gollux** [comment]
The code is indeed incorrect: `erase` on an `unordered_map` is documented to invalidate iterators.

It's hard to tell what exactly happens. Different container managers can set up control groups in different ways (which is why it is not recommended to run Isolate in containers). Additionally, you have address space randomization turned on, so the behavior is likely not deteriministic.

Are you using the same system (compilers, libraries, etc.) in both scenarios?

**Comment by ysabih2** [comment]
@gollux Thanks for looking into this.

> Are you using the same system (compilers, libraries, etc.) in both scenarios?
Yes, the same Docker image is used in both scenarios.

Since applying the address space size limit works, this is no longer issue. I just wanted to make sure this is not a sandboxing bug, which it doesn't seem to be.
