### ISSUE TITLE
Does the current release or git master support `cgroup v2` by default?

### ISSUE THREAD

**Issue by jiapei100** [ioi/isolate#172]
- [2.0](https://github.com/ioi/isolate/releases/tag/v2.0)
- [master](https://github.com/ioi/isolate/archive/refs/heads/master.zip)

Wondering if `cgroup v2` is supported by `isolate` by default ?

Cheers
Pei

**Comment by gollux** [comment]
The current master branch (Isolate 2.0) supports cgroup v2 only.

**Comment by jiapei100** [comment]
@gollux 

Wow... Thank you so much for your prompt response.

A further question if you can give me a hand?

I'm actually playing with [judge0](https://github.com/judge0/judge0), which seems to support `cgroup v1` only so far.
I think [judge0](https://github.com/judge0/judge0) requires a sandbox anyway, right? will these two work together? I mean: will `cgroup v1` [judge0](https://github.com/judge0/judge0) work with current `cgroup v2` [isolate](https://github.com/ioi/isolate)???

**Comment by gollux** [comment]
Sorry, I have no idea on internals of judge0. Perhaps it requires cgroup v1 because it uses an older version of Isolate? I recommend contacting the developers of judge0.
