### ISSUE TITLE
Consistency of API (wall-time/time-wall)

### ISSUE THREAD

**Issue by seirl** [ioi/isolate#20]
The wall-time option is wall-time and the output is time-wall. Could this be changed to be more consistent?

**Comment by Zopieux** [comment]
That's a matter of changing [that line](/ioi/isolate/blob/7f55e36a27c17f07bd90e254d0eadefdac09a4d6/isolate.c#L93).

**Comment by Zopieux** [comment]
Nobody's crazy enough to parse thing kind of output, are they?

**Comment by stefano-maggiolo** [comment]
We are! :)
(cms-dev/cms)

**Comment by gollux** [comment]
> Nobody's crazy enough to parse thing kind of output, are they?

Do you have anything in mind what would be more appropriate for parsing? :-)

I agree that it is a little bit inconsistent, but breaking a documented
public interface of Isolate needs a much stronger reason.
