### ISSUE TITLE
Can isolate limit the size of output file? 

### ISSUE THREAD

**Issue by joeyac** [ioi/isolate#22]
Can isolate limit the size of output file?

**Comment by gollux** [comment]
Not particularly of the output file.

You can however limit sizes of all files created by the sandboxed
program using the --fsize option, or use disk quota to limit total
size of all files generated (the --quota option).

**Comment by joeyac** [comment]
i find it.The Isolate's manual page should update.

**Comment by joeyac** [comment]
Thank you very much.

**Comment by gollux** [comment]
> i find it.The Isolate's manual page should update.

What is missing there?

**Comment by joeyac** [comment]
Not very important,something like --fsize,--slient options which can be found on isolate --help do not mention there.

**Comment by gollux** [comment]
> Not very important,something like --fsize,--slient options which can be found on isolate --help do not mention there.

They are both in the OPTIONS section, aren't they?

**Comment by joeyac** [comment]
![image](https://cloud.githubusercontent.com/assets/18542850/21576991/1ae48b84-cf84-11e6-8e20-971cbb07a319.png)
but i just find this...
