### ISSUE TITLE
Failed to create control group

### ISSUE THREAD

**Issue by hermanzdosilovic** [ioi/isolate#24]
Hi,

when running `isolate --cg --init` as `root` user I get following error:
```
Failed to create control group /sys/fs/cgroup/memory/box-0/: No such file or directory
```

Running above command without `--cg` option returns me box path (as expected):
```
/var/local/lib/isolate/0
```

Why am I getting this error?

**Comment by gollux** [comment]
Hi,

do you have cgroups enabled on your system? Is there /sys/fs/cgroup/?

**Comment by hermanzdosilovic** [comment]
This is output of `ls -l /sys/fs/cgroup/`:
```
dr-xr-xr-x 3 root root  0 Feb  5 11:07 blkio
lrwxrwxrwx 1 root root 11 Jan 26 11:02 cpu -> cpu,cpuacct
lrwxrwxrwx 1 root root 11 Jan 26 11:02 cpuacct -> cpu,cpuacct
dr-xr-xr-x 3 root root  0 Feb  5 11:07 cpu,cpuacct
dr-xr-xr-x 3 root root  0 Feb  5 11:07 cpuset
dr-xr-xr-x 3 root root  0 Feb  5 11:07 devices
dr-xr-xr-x 3 root root  0 Feb  5 11:07 freezer
lrwxrwxrwx 1 root root 16 Jan 26 11:02 net_cls -> net_cls,net_prio
dr-xr-xr-x 3 root root  0 Feb  5 11:07 net_cls,net_prio
lrwxrwxrwx 1 root root 16 Jan 26 11:02 net_prio -> net_cls,net_prio
dr-xr-xr-x 3 root root  0 Feb  5 11:07 perf_event
dr-xr-xr-x 5 root root  0 Feb  5 11:07 systemd
```

As I understood from docs, I only need to use `--cg` when I want to use `--cg-timing` or `--cg-mem`?

**Comment by gollux** [comment]
> This is output of `ls -l /sys/fs/cgroup/`:

This looks like you do not have memory cgroups enabled on your system.
Please look at the INSTALLATION section of the man page.

> As I understood from docs, I only need to use `--cg` when I want to use `--cg-timing` or `--cg-mem`?

Yes.
