### ISSUE TITLE
Can we get max USS from isolate?

### ISSUE THREAD

**Issue by joeyac** [ioi/isolate#30]

**Comment by gollux** [comment]
What is USS?

**Comment by joeyac** [comment]
RSS- Resident Set Size
USS- Unique Set Size
"USS is the total private memory for a process, i.e. that memory that is completely unique to that process.USS is an extremely useful number because it indicates the true incremental cost of running a particular process. When a process is killed, the USS is the total memory that is actually returned to the system. USS is the best number to watch when initially suspicious of memory leaksin a process."

**Comment by gollux** [comment]
I do not think it is so useful: whenever a program uses a shared
library, it is highly unpredictable which parts of the library will
be accounted in the USS of the process and which will not. And shared
libraries are usually the only kind of non-private memory used by
contest programs.

Do you have any interesting use case for USS?

**Comment by joeyac** [comment]
I am just interested in it, thank you for help me out~

**Comment by joeyac** [comment]
And can I use your sandbox in my Online Judge system?

**Comment by gollux** [comment]
> And can I use your sandbox in my Online Judge system?

Sure, why not?

**Comment by joeyac** [comment]
Thank you.
