### ISSUE TITLE
Use execvpe instead of execve?

### ISSUE THREAD

**Issue by xelez** [ioi/isolate#39]
I'm talking about this line:
https://github.com/ioi/isolate/blob/a86f4a7ee165075a3356d77d9c7384304d64df9d/isolate.c#L594

Rationale: no need for full paths when specifying command to run.

Not sure if it's a good idea, although.

**Comment by gollux** [comment]
I think it is not a good idea. The sandbox should depend on the outside
environment as little as possible.

**Comment by xelez** [comment]
Fair point, closing.
