### ISSUE TITLE
Error in config file, line 0: Configuration is not complete

### ISSUE THREAD

**Issue by Silverutm** [ioi/isolate#45]
Can't configure Isolate
After running
root@computer:/usr/local/etc/isolate# make isolate
and
root@computer:/usr/local/etc/isolate# ./isolate-check-environment --execute

and everything has a PASS on it, I can't run :

root@computer:/usr/local/etc/isolate# ./isolate --init
The next message appears, but can't figure out what is the missing configuration

"Error in config file, line 0: Configuration is not complete"

**Comment by gollux** [comment]
You really should not build isolate in /usr/local/etc/isolate.
This is the expected location of the configuration file and you
are making a directory there :)

Unpack the sources somewhere else (e.g., in /tmp/isolate) and run
"make" and "make install".
