### ISSUE TITLE
cgroups functionality doesn't work with linux 4.15

### ISSUE THREAD

**Issue by tudurom** [ioi/isolate#50]
Hi,

I just upgraded to Linux kernel 4.15 and it looks like isolate is broken because there is no more `/sys/fs/cgroup/cpuacct` here. I checked the man page and it looks like it has been replaced by `cpu`. I don't know too much about control groups and how isolate uses them, take this with a grain of salt.

**Comment by gollux** [comment]
Sorry for the delay. I just checked with Linux 4.17.6 and it seems that cpuacct is still there as a symlink to "cpu,cpuacct". Could it be related to how your distribution sets up the cgroups?

**Comment by tudurom** [comment]
Time passed, it works for me now. The distro is Arch Linux. Thank you for
the clarification!
