### ISSUE TITLE
execve("/usr/bin/javac")  No such file or directory

### ISSUE THREAD

**Issue by Silverutm** [ioi/isolate#51]
When trying to compile a java program with command

isolate --full-env --cg -p --time=5 --meta=log.txt --stderr=error.txt --run -- javac code.java

I receive the following message
execve("/usr/bin/javac")  No such file or directory

Note:
$ which javac
/usr/bin/javac

**Comment by Zopieux** [comment]
There is a good chance this is a symlink to handle various versions of Java. Debian does this for its *alternatives* system. Try with the real path:

```bash
$ realpath $(which javac)
/something/something/javac
```
