### ISSUE TITLE
Run command in single quote not working

### ISSUE THREAD

**Issue by thinkgear** [ioi/isolate#53]
when i run this command, 
``isolate --run -- '/usr/bin/g++ -lm -W -o code code.cpp'``

the following error comes.
**execve("/usr/bin/g++ -lm -W -o code code.cpp" ): No such file or directory**

But if I run without quote it runs properly but number of process count have to increased from 1

**Comment by gollux** [comment]
Both are perfectly correct :)

In the first case, you tried to run a command with a lot of spaces in its name and passed it no arguments.

In the second case, g++ is just a simple driver which executes the right parts of the compiler as separate processes, so multiple processes are expected.

**Comment by thinkgear** [comment]
The command I tried is without spaces and i have passed all the arguments to it, but all it in quote.
The same command works in second case. Can you explain with example where I am going wrong?

**Comment by gollux** [comment]
"isolate --run -- a b c" runs a program "a" with parameters "b" and "c".
"isolate --run -- 'a b c'" runs a program "a b c", which is not likely to exist.
