### ISSUE TITLE
Configuration is not complete.

### ISSUE THREAD

**Issue by Vasilut** [ioi/isolate#54]
Hi. I tried to run "--init" command but I got the next error:
Error in config file, line 0: Configuration is not complete. 

I ran the sandbox in an ubuntu-16.04.4-desktop-amd64 environment. The command that I try to execute in terminal is : sudo ./isolate --init

Thanks.

**Comment by Zopieux** [comment]
What does your isolate config file (``/etc/isolate`` by default) contain?

**Comment by Vasilut** [comment]
My directory contains: 
![defaultsandbox](https://user-images.githubusercontent.com/15065289/39877123-bbd6343c-547d-11e8-849f-e9e014b35bb6.PNG)

The configuration file contains:
![sandboxconfig](https://user-images.githubusercontent.com/15065289/39877186-e857595a-547d-11e8-8d8d-7a34c808fd3b.PNG)

Thanks.

**Comment by gollux** [comment]
This means that some of the configuration settings are missing
in your configuration file. Please check that it is correct,
for example by compariting it to default.cf.

**Comment by BarishNamazov** [comment]
@Vasilut any fixes you did for this error?

**Comment by BarishNamazov** [comment]
Nevermind, got it. Create a *file* `/usr/local/etc/isolate` which will serve as config file. Put contents of `default.cf` into it.
