### ISSUE TITLE
Redirect standard output

### ISSUE THREAD

**Issue by Vasilut** [ioi/isolate#58]
Hello.

I have the next simple code:

     #include <iostream>
     #include <fstream>
     using namespace std;

       int main()
       {
	   int n;
	   cin >> n;
	
	   cout << " Number is: " << n;
	
	   return 0;
      }

I want to evaluate this program and to redirect the standard input and the standard output. I ran the next command: **./isolate --cg --meta=/tmp/muc2.txt --stdin=test1.in --stdout=fis1.out --cg-mem=3000 --time=2 --run -- prog**  
After I ran this command , in my sandbox folder the file "fis1.out" was generated and contains the results. My question is, I can redirect the output file to be created in another folder (not in the sandbox folder) ?

Thanks

**Comment by gollux** [comment]
Sorry for the delayed answer. This is currently not supported: stdin/stdout is redirected when the process has already entered the sandbox, so you do cannot access any files outside.

**Comment by bblackham** [comment]
Note that you can achieve this by performing redirections on the isolate invocation. e.g.:

./isolate --cg --meta=/tmp/muc2.txt --cg-mem=3000 --time=2 --run -- prog < test1.in > fis1.out

**Comment by Silverutm** [comment]
Or you could copy the files to the desired folder
`cp rute_to_isolate/file my_awesome_route/file`
