### ISSUE TITLE
-b shorthand for --box-id doesn't seem to work

### ISSUE THREAD

**Issue by whiteShtef** [ioi/isolate#59]

**Comment by gollux** [comment]
It works for me. What exactly happens on your machine?

**Comment by whiteShtef** [comment]
when I provide the `-b` flag and box id, it seems to ignore it and tries to init a box with the id of 0.

```bash
sbr@hiltrud ~ $ isolate --box-id=5 --init
/var/local/lib/isolate/5
sbr@hiltrud ~ $ isolate --box-id=5 --cleanup
sbr@hiltrud ~ $ isolate -b=5 --init
/var/local/lib/isolate/0

```

**Comment by whiteShtef** [comment]
Sorry. Just noticed that you aren`t supposed to place `=` after a flag.
Wouldn't be bad to write this somewhere in the docs.

**Comment by gollux** [comment]
Ah well... we definitely should complain that "=5" is not a number instead of parsing it as 0 silently. I will add a check.
