### ISSUE TITLE
execve is throwing "No such file or directory" for a statically-linked executable

### ISSUE THREAD

**Issue by minhducsun2002** [ioi/isolate#63]
Running statically compiled C programs failed.
```
# isolate --run -- "./a" --time=1
execve("./a"): No such file or directory
```

The source code of the program is a simple `while(1){};` wrapped in `int main()`, compiled with `gcc -static -no-pie`.

The existence of the `a` executable in the directory `isolate` was invoked can be confirmed.

**Comment by gollux** [comment]
You should place the executable in the sandbox directory instead,
that is the directory printed by `isolate --init`.

**Comment by minhducsun2002** [comment]
I ran the command above from the sandbox directory.

**Comment by gollux** [comment]
When you mention "sandbox directory", is it the directory
printed by "isolate --init"?

**Comment by minhducsun2002** [comment]
Yes.

**Comment by minhducsun2002** [comment]
Actually, I ran `cd $(isolate --init)` though.
(Afterward I can still confirm it's the sandbox directory.)

**Comment by gollux** [comment]
If you still experience the problem, please send me the executable file with which it fails.

**Comment by minhducsun2002** [comment]
Here I am bundling the source code and the executable itself.
[a.zip](https://github.com/ioi/isolate/files/2720866/a.zip)
```
/var/local/lib/isolate/0 # isolate --run -- ./a --time=1
execve("./a"): No such file or directory
/var/local/lib/isolate/0 # ls 
a
```

**Comment by gollux** [comment]
/var/local/lib/isolate/0 should contain a "box" subdirectory
(created by isolate --init), where you should put your executable.

**Comment by minhducsun2002** [comment]
Okay, problem solved. Thank you very much for your support.

But, however. (You may have seen that the source code contains only an infinite loop.)
```
# isolate --run -- a --time=1 --wall-time=1
```
It's there for over 2 seconds.

**Comment by gollux** [comment]
> ```
> # isolate --run -- a --time=1 --wall-time=1
> ```

This passes the options to the executable inside the sandbox.
For options to apply to isolate itself, you must specify them
before the "--" separator.

**Comment by minhducsun2002** [comment]
Okay, the program stopped now.

Thank you very much!

_I wanted to ask for a long time but it seems like digging through the source code was kinda too tedious. :)_

**Comment by gollux** [comment]
> _I wanted to ask for a long time but it seems like digging through the source code was kinda too tedious. :)_

Digging in the manual would suffice ;)

**Comment by minhducsun2002** [comment]
Sorry, my fault. Have a nice day ;)
> isolate options --run -- program arguments

(http://www.ucw.cz/moe/isolate.1.html)
