### ISSUE TITLE
"Crashes" on Ubuntu 18.10

### ISSUE THREAD

**Issue by t-lenz** [ioi/isolate#64]
On Ubuntu 18.10, `isolate`  quits with error message `Caught fatal signal 11` when run with infinite stack limit (i.e. with no `--stack` parameter given). Strangely, however there seems to be some interplay with other parameters. More precisely, the above always happens in the following cases:

- when used inside CMS for evaluating a submission
- when run as `isolate --env=HOME=. --run -- ./test` (where `test` just prints `hi`); the same happens with other `HOME` paths

In both cases everything is fine once we supply `--stack=<large integer>`. However, `isolate` works just fine even with infinite stack limit in the following cases:

- when used inside CMS for _compiling_ a submission
- when run as `isolate --run -- ./test`

While it is possible to work around this issue for usage in CMS (cf. e.g. [this branch](https://github.com/ioi-germany/cms/tree/ubuntu_workaround)) it would be preferrable if this could be fixed in `isolate` directly.

(To be entirely precise, this happens in the German fork of CMS; however, this uses just the same version of `isolate` as the current cms-dev main branch. The above error occurs on two different computers, one of them with a completely fresh Ubuntu install.)

**Comment by seirl** [comment]
Maybe this has to do with #42 and #43 ?

What's your kernel version?

**Comment by t-lenz** [comment]
It's 4.18.0-10-generic.

**Comment by pehrsoderman** [comment]
I seem to have encountered the same problem on Ubuntu 18.10 with a 4.18.0-13-generic Kernel. Any recommendations for how to work around it?

**Comment by pehrsoderman** [comment]
Some additional information: 

I get the following message in the syslog: 

`2019-01-02T21:48:00.633297+01:00 pehrs kernel: [896241.606886] traps: isolate[1622] general protection ip:7ffff7c52cdd sp:7fffffffd9f8 error:0 in libc-2.28.so[7ffff7be5000+171000]`

Also attaching a systrace from running isolate, which might help.
[strace.log](https://github.com/ioi/isolate/files/2722022/strace.log)

The strace was generated running the following commands: 

```
pehrs@pehrs:~$ sudo /usr/local/bin/isolate --box-id=0 --cg --cg-timing --processes=128 --env=HOME=/ --env=PATH --env=LANG --dir=/usr= --dir=/usr/lib/ --dir=/etc/alternatives/ --dir=/usr/bin/ --dir=/usr/include/ --dir=/usr/local/lib/ --dir=/usr/share/pyshared/ --env=PYTHONDONTWRITEBYTECODE=1 --env=PYTHONIOENCODING=UTF-8 --dir=/src=/var/lib/kattis/run/subs/comp_158309_206449/compile:rw:noexec --quota=40960,40960  --init
/var/local/lib/isolate/0
pehrs@pehrs:~$ sudo strace /usr/local/bin/isolate --box-id=0 --cg --cg-timing --processes=128 --env=HOME=/ --env=PATH --env=LANG --dir=/usr= --dir=/usr/lib/ --dir=/etc/alternatives/ --dir=/usr/bin/ --dir=/usr/include/ --dir=/usr/local/lib/ --dir=/usr/share/pyshared/ --env=PYTHONDONTWRITEBYTECODE=1 --env=PYTHONIOENCODING=UTF-8 --dir=/src=/var/lib/kattis/run/subs/comp_158309_206449/compile:rw:noexec --stderr=/src/__stderr --meta=/var/lib/kattis/run/subs/comp_158309_206449/compile.meta_file --chdir=/src --time=60 --wall-time=120 --cg-mem=1048580 --run -- /usr/bin/python2 -m py_compile ./hello.py 2> strace.log
```

**Comment by pehrsoderman** [comment]
Here is a core dump also: 

[core.isolate.tar.gz](https://github.com/ioi/isolate/files/2723437/core.isolate.tar.gz)

I am not sure how helpful it is: 

```
pehrs@pehrs:/tmp$ gdb /usr/local/bin/isolate core.2.isolate
GNU gdb (Ubuntu 8.2-0ubuntu1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/isolate...(no debugging symbols found)...done.
[New LWP 2]
Core was generated by `/usr/local/bin/isolate --box-id=0 --cg --cg-timing --processes=128 --env=HOME=/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ffff7c52cdd in _IO_str_init_static_internal (sf=sf@entry=0x7fffffffda28, ptr=ptr@entry=0x7fffffffdce8 "", size=size@entry=1023, 
    pstart=pstart@entry=0x7fffffffdce8 "") at strops.c:41
41	strops.c: No such file or directory.
(gdb) 
```

**Comment by pehrsoderman** [comment]
@seirl @gollux Could you offer any advice on this?

**Comment by bblackham** [comment]
Some libc code now expects the stack to be 16-byte aligned (to use movaps instruction). The way in which the child process is spawned doesn't adhere to this. Here's a quick fix:

```
--- a/isolate.c
+++ b/isolate.c
@@ -814,7 +814,7 @@ run(char **argv)

   proxy_pid = clone(
     box_proxy,                 // Function to execute as the body of the new process
-    argv,                      // Pass our stack
+    (void*)((uintptr_t)argv & ~15),                    // Pass our stack, aligned to 16-bytes.
     SIGCHLD | CLONE_NEWIPC | (share_net ? 0 : CLONE_NEWNET) | CLONE_NEWNS | CLONE_NEWPID,
     argv);                     // Pass the arguments
   if (proxy_pid < 0)
```

@gollux: do you have any better suggestions?

**Comment by gollux** [comment]
> @gollux: do you have any better suggestions?

No, this looks like the right thing to do. Thanks, Bernard!
