### ISSUE TITLE
Cannot use --dir option

### ISSUE THREAD

**Issue by kubapat** [ioi/isolate#65]
Hello!
I downloaded and successfully set up isolate on my 2nd computer (I've used it before on my server). But now I'm encountering problems with --dir option.
The easiest sample. I have file ab in /something directory i use this command

`sudo isolate --dir=/something/:rw --run /something/ab`

I get this error:
`execve("/something/ab"): No such file or directory`

When I do -vv option I get:

```
Started proxy_pid=21774 box_pid=21775 box_pid_inside_ns=2
Binding ./box on box (flags 1006)
Binding /bin on bin (flags 1007)
Binding /dev on dev (flags 1003)
Binding /lib on lib (flags 1007)
Binding /lib64 on lib64 (flags 1007)
Mounting proc on proc (flags 5)
Binding ./tmp/tmp on tmp (flags 1006)
Binding /usr on usr (flags 1007)
Binding //something/ on something/ (flags 1006)
Passing environment:
	LIBC_FATAL_STDERR_=1
```

What I'm doing wrong?

Thanks in advance

Best Regards

**Comment by gollux** [comment]
I am unable to reproduce this problem. Is your /something/ab statically linked, or are you sure that all shared libraries it depends on are available in the sandbox? Is `/something` really that string, or it is a more complicated name including sub-directories?
