### ISSUE TITLE
Quota argument does not work properly

### ISSUE THREAD

**Issue by horacekj** [ioi/isolate#67]
`isolate ... -q100,100 ...` produces 
```
Invalid numeric parameter: 100,100
```

This is probably due to the the fact that variable `optarg` points to `100,100` when calling `opt_uint` at line 1036.

**Comment by gollux** [comment]
Ah, this one is a victim of switching to strict parsing of numbers. Will fix in a minute.

**Comment by simonlindholm** [comment]
I think the fix for this was buggy: it first does `*sep++ = 0;` to overwrite the comma, then later `inode_quota = opt_uint(sep+1);`, skipping the first digit.

**Comment by gollux** [comment]
Sorry, it should be right now. Released 1.8.1 with a fix.
