### ISSUE TITLE
How to properly use no default dirs

### ISSUE THREAD

**Issue by ekremski** [ioi/isolate#71]
Hi!
 I've recently started using isolate in my personal online judge. I'm using the command shown below
`sudo isolate --cg --dir=/dir/to/mount/:rw --mem=MEM_SIZE --stack=8096 --time=TIME_LIMIT --stdin=/dir/to/mount/1.in --stdout=/dir/to/mount/1.out --meta=/dir/to/mount/memory.txt --fsize=102400 --stderr=/dir/to/mount/error.data  --run -- /dir/to/mount1` and everything works fine, but when I try to add -D (no default dirs) option I'm experiencing error `Cannot change current directory: No such file or directory.` How to change my command to make my execution as safe as possible simulataneously using *in file, *out file, META file, time & memory restrictions and no default dirs (Just to prevent hacking my OJ)?

**Comment by gollux** [comment]
Hello! You need at least something like the default rule "box=./box:rw", so
that the /box directory exists inside the sandbox. However, many binaries
also need `/dev/zero`, `/dev/null`, and similar devices.
