### ISSUE TITLE
How to use different env of python

### ISSUE THREAD

**Issue by rohanraarora** [ioi/isolate#73]
I have been using isolate in a project where I need to run a few python programs for data science problems. I am able to run isolate with the default python env i.e. `/usr/bin/python3` but if I change this to a diff env such as anaconda python env ( `/opt/conda/bin/python3` ) then I get an exception `execve("/opt/conda/bin/python3"): No such file or directory` . So how can I use anaconda python env to run my programs?

**Comment by gollux** [comment]
Do you have a directory rule for /opt set up? Otherwise, /opt is not present
inside the sandbox.

**Comment by rohanraarora** [comment]
No, I am not using any directory rule. I am not sure how to use it properly. Can you share an example to do so? Thanks in advance.

**Comment by gollux** [comment]
Did you read the manual page? The rules are described there in quite a detail.

**Comment by rohanraarora** [comment]
Got it, thanks.
