### ISSUE TITLE
Release with the Ubuntu 16.10 fix

### ISSUE THREAD

**Issue by pehrsoderman** [ioi/isolate#75]
Would it be possible to get a tagged release with the fix for Ubuntu 18.10 in it?

**Comment by gollux** [comment]
We will have a preparatory meeting for the IOI next week and I hope I will
release the new version of Isolate there.

**Comment by pehrsoderman** [comment]
@gollux Sounds good. Much appreciated!

**Comment by gollux** [comment]
Done. I caught one more bug and released isolate-1.8.

**Comment by pehrsoderman** [comment]
@gollux Can you have a look at the issue reported by @simonlindholm (https://github.com/ioi/isolate/issues/67#issuecomment-465353495) and possibly do a .1 release with that fixed?

**Comment by gollux** [comment]
I will. On the airplane from Baku, I also realized one potential problem with
the last-minute bugfix of time limit reporting. I will release a .1 quite soon.

**Comment by pehrsoderman** [comment]
@gollux Any update on the .1?

**Comment by gollux** [comment]
> @gollux Any update on the .1?

Sorry for the delay. It turned out that the last-minute fix of run
time reporting could cause security issues (some processes in the control
group not being killed properly) and I needed some time to think about
the right fix.

I tagged 1.8.1 a couple of seconds ago.
