### ISSUE TITLE
Unable to timeout blocking code

### ISSUE THREAD

**Issue by rohanraarora** [ioi/isolate#76]
I am using isolate to run unsafe code inside docker environment for quite some time. 
Usually isolate does the job and kills long running code after the time limit but isolate is unable to kill blocking python code.

```
import queue
q = queue.Queue()
q.get()
```

Above code doesn't get killed even after using the timeout option. `get()` method of `Queue` class is a [blocking code](https://docs.python.org/3/library/queue.html#queue.Queue.get).
How to timeout the above code? TIA.

**Comment by gollux** [comment]
Did you set the wall clock limit?

**Comment by rohanraarora** [comment]
Wall clock limit does the job as expected. Thanks.
