### ISSUE TITLE
pivot_root as security measure

### ISSUE THREAD

**Issue by josalhor** [ioi/isolate#79]
I couldn't find any reference on this repo about pivot_root. It can be used together with chroot; was it ever considered as a security measure? Would there be any drawbacks in adding it?

**Comment by seirl** [comment]
I'm not sure what you would want to achieve with `pivot_root`. It's typically used by the initrd to make the kernel use the newly mounted file system as its root, it has little to do with isolation.

**Comment by josalhor** [comment]
My guess was, and correct me if I'm wrong here, that changing the root of the file system, as opposed as moving the root directory, prevents accessing the mountpoints over the new root directory through the Virtual File System.

**Comment by seirl** [comment]
Again, `pivot_root` is intended to be used by the initrd. It cannot be used here.

**Comment by gollux** [comment]
I also don't see how to use pivot_root as a security mechanism. I am closing this issue, but if you have any relevant way how to use pivot_root in a sensible way, feel free to re-open it.
