### ISSUE TITLE
Are --init and --cleanup really necessary?

### ISSUE THREAD

**Issue by seirl** [ioi/isolate#8]
The `--init` and `--cleanup` options need to be called everytime we want an isolated program to be run. The only thing they do is to create the directories and initialize the cgroups and the quotas. These operations are not really costly in time. Why couldn't we run them directly before and after running the program with `--run`?

The benefits would be:

* A simpler interface (only call `isolate <options> -- <cmd>`)
* No need for the caller to manage a pool of box ids themself
* No need to remember to init and cleanup the boxes, this is done automatically
* Simplify the code a lot (no more "modes", warnings for boxes that were not created, etc.)

I can work on that if you think this change is worth it, I already have prepared some changes.

Is there a rationale behind having these two separate options?

**Comment by gollux** [comment]
Hello!

> The `--init` and `--cleanup` options need to be called everytime we want an
> isolated program to be run. The only thing they do is to create the
> directories and initialize the cgroups and the quotas. These operations are
> not really costly in time. Why couldn't we run them directly before and
> after running the program with `--run`?

You forget two things:

(1) You have to put files to the sandbox before the isolated program is run
(e.g., the program's binary :)) and fetch the files generated by the program
afterwards.

(2) Isolate has to tell you where the sandbox directory lies. You must not
assume that it is a fixed location: it can differ from system to system.

I do not see how to do this easily with just a single invocation of isolate.
Currently, we to this:

(a) Call `isolate --init`. This creates a clean sandbox and tells you its
location.

(b) You populate the directory with whatever you need.

(c) Call `isolate --run`.

(d) You fetch the results from the directory.

(e) Call `isolate --cleanup`. This deletes the contents of the directory.

I will gladly hear any idea how to simplify this.

**Comment by seirl** [comment]
Hi!

You're right, I had not thought about this way of using it. I was mounting the directory containing the binary using -d, but I agree that using --init that way looks much simpler.
