### ISSUE TITLE
Disable System Calls

### ISSUE THREAD

**Issue by pratikdaigavane** [ioi/isolate#88]
I have made an online IDE using isolate https://moc.interviewmocha.com/
Is there any way that I can completely disable system calls for all languages?

For example 
in Python: 
`os.system()` or `subprocess.call()`

in CPP
`system()`

**Comment by gollux** [comment]
No, Isolate is not a tool for filtering system calls.
Why do you want to do that? The program running inside Isolate can reach only what you made available in the sandbox, so there is little use in restricting syscalls.

**Comment by pratikdaigavane** [comment]
Thanks!
