### ISSUE TITLE
An error occurred when I compiled with GCC

### ISSUE THREAD

**Issue by Zeng1998** [ioi/isolate#99]
ubuntu 20.04
isolate latest

The following are my operations and errors, I have no idea what happened
```
isolate --init
isolate -b 0 --run /usr/bin/gcc main.c
```

main.c
```c
int main(){
    printf("hello world\n");
    return 0;
}
```

the error
```
gcc: error: vfork: Resource temporarily unavailable
Exited with error status 1
```

**Comment by hermanzdosilovic** [comment]
I think you should add the `-p` flag to allow GCC to `fork`.

Thus, your command would be: `isolate -b 0 -p --run /usr/bin/gcc main.c`.

**Comment by Zeng1998** [comment]
> I think you should add the `-p` flag to allow GCC to `fork`.
> 
> Thus, your command would be: `isolate -b 0 -p --run /usr/bin/gcc main.c`.

Yes, you're right. Thanks
